import sbt.{CrossVersion, Def, compilerPlugin, _}
import sbt.Keys._

object SilencerSettings {
  // stop "unused import" warnings from routes files
  def apply(): Seq[Def.Setting[_ >: Seq[ModuleID] with Task[Seq[String]] <: Equals]] = Seq(
    libraryDependencies ++= Seq(
      compilerPlugin("com.github.ghik" % "silencer-plugin" % "1.7.12" cross CrossVersion.full),
      "com.github.ghik" % "silencer-lib" % "1.7.12" % Provided cross CrossVersion.full
    ),
    // silence all warnings on autogenerated files
    scalacOptions += "-P:silencer:pathFilters=target/.*",
    // Make sure you only exclude warnings for the project directories, i.e. make builds reproducible
    scalacOptions += s"-P:silencer:sourceRoots=${baseDirectory.value.getCanonicalPath}"
  )
}
